services:
  db:
    image: postgres:16-alpine
    container_name: pitflow-postgres
    environment:
      POSTGRES_DB: pitflow_os
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pitflow_os"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: pitflow-os-backend
    ports:
      - "8080:8080"
    environment:
      # TODO: Mover para variáveis de ambiente no futuro
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pitflow_os
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_SECRET=${JWT_SECRET:-digimon-digimon-digitais-digimons-sao-campeoes-123456789}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
