spring:
  application:
    name: pitflow-os-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pitflow_os}
    username: ${DB_USERNAME:pitflow}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    #show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:pitflow.notifications@gmail.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  forward-headers-strategy: framework

logging:
  level:
    org:
      liquibase: INFO

api:
  security:
    token:
      secret: ${JWT_SECRET}
      expiration-hours: 3
  url: ${API_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

  endpoint:
    health:
      show-details: never

  health:
    mail:
      enabled: false

  tracing:
    enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
      service: pitflow-os-backend

  datadog:
    metrics:
      export:
        enabled: ${DATADOG_ENABLED:false}
        api-key: ${DATADOG_API_KEY}
        uri: https://api.us5.datadoghq.com
        step: 30s

mock:
  send-message: ${MOCK_MESSAGE:true}

