apiVersion: v1
kind: ConfigMap
metadata:
  name: pitflow-config
  labels:
    app: pitflow-backend
data:
  DB_HOST: "${RDS_ENDPOINT}"
  DB_PORT: "5432"
  DB_NAME: "pitflow_os"
  DB_USER: "pitflow"
  API_PUBLIC_URL: "${API_PUBLIC_URL}"
  MOCK_MESSAGE: "${MOCK_MESSAGE}"
