apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitflow-backend
  namespace: pitflow
  labels:
    app.kubernetes.io/name: pitflow-backend
    app.kubernetes.io/instance: pitflow-backend
    app.kubernetes.io/component: operation
    app.kubernetes.io/part-of: pitflow
    app.kubernetes.io/managed-by: github-actions
    tags.datadoghq.com/env: "producao"
    tags.datadoghq.com/service: "pitflow-os-backend"
    tags.datadoghq.com/version: "1.0.0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pitflow-backend
      app.kubernetes.io/instance: pitflow-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pitflow-backend
        app.kubernetes.io/instance: pitflow-backend
        app.kubernetes.io/component: operation
        app.kubernetes.io/part-of: pitflow
        app.kubernetes.io/managed-by: github-actions
        tags.datadoghq.com/env: "producao"
        tags.datadoghq.com/service: "pitflow-os-backend"
        tags.datadoghq.com/version: "${IMAGE_VERSION}"
      annotations:
        # Injeção do agente do datadag
        admission.datadoghq.com/java-lib.version: "latest"
    spec:
      containers:
        - name: pitflow-backend
          # O placeholder abaixo será substituído pela URL do ECR na Pipeline
          image: ${CONTAINER_IMAGE}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "700m"
              memory: "1Gi"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=25"
            # Agora lendo o Host dinâmico do ConfigMap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pitflow-backend-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pitflow-backend-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: pitflow-backend-config
                  key: DB_USERNAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pitflow-backend-config
                  key: DB_PORT
            # Mantendo os Secrets para dados sensíveis
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pitflow-backend-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pitflow-backend-secrets
                  key: jwt-secret
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: pitflow-backend-config
                  key: API_PUBLIC_URL
            - name: MOCK_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: pitflow-backend-config
                  key: MOCK_MESSAGE
            - name: REGISTRY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: pitflow-backend-config
                  key: REGISTRY_SERVICE_URL
            - name: INVENTORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: pitflow-backend-config
                  key: INVENTORY_SERVICE_URL
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pitflow-backend-secrets
                  key: mail-username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pitflow-backend-secrets
                  key: mail-password
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pitflow-backend-secrets
                  key: datadog-api-key
            - name: DATADOG_ENABLED
              value: "true"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 15  # Tentar por até 15 * 10s = 150s total
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
