apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitflow-backend
  labels:
    app: pitflow-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: pitflow-backend
  template:
    metadata:
      labels:
        app: pitflow-backend
    spec:
      containers:
        - name: pitflow-backend
          # O placeholder abaixo será substituído pela URL do ECR na Pipeline
          image: ${CONTAINER_IMAGE}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "700m"
              memory: "1Gi"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=50"
            # Agora lendo o Host dinâmico do ConfigMap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pitflow-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pitflow-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: pitflow-config
                  key: DB_USER
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pitflow-config
                  key: DB_PORT
            # Mantendo os Secrets para dados sensíveis
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pitflow-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pitflow-secrets
                  key: jwt-secret
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 15  # Tentar por até 15 * 10s = 150s total
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5