apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pitflow-backend
  namespace: pitflow
  labels:
    app.kubernetes.io/name: pitflow-backend
    app.kubernetes.io/instance: pitflow-backend
    app.kubernetes.io/component: operation
    app.kubernetes.io/part-of: pitflow
    app.kubernetes.io/managed-by: github-actions
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pitflow-backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
