apiVersion: v1
kind: Secret
metadata:
  name: pitflow-backend-secrets
  namespace: pitflow
  labels:
    app.kubernetes.io/name: pitflow-backend
    app.kubernetes.io/instance: pitflow-backend
    app.kubernetes.io/component: operation
    app.kubernetes.io/part-of: pitflow
    app.kubernetes.io/managed-by: github-actions
type: Opaque
stringData: # Vars will be filled by GithubActions, the k8s transform in base64
  db-password: "${DB_PASSWORD}"
  jwt-secret: "${JWT_SECRET}"
  mail-username: "${MAIL_USERNAME}"
  mail-password: "${MAIL_PASSWORD}"
  datadog-api-key: "${DATADOG_API_KEY}"
