apiVersion: v1
kind: Secret
metadata:
  name: pitflow-secrets
type: Opaque
stringData: # Vars will be filled by GithubActions, the k8s transform in base64
  db-password: "${DB_PASSWORD}"
  jwt-secret: "${JWT_SECRET}"