apiVersion: v1
kind: Service
metadata:
  name: pitflow-backend
  namespace: pitflow
  labels:
    app.kubernetes.io/name: pitflow-backend
    app.kubernetes.io/instance: pitflow-backend
    app.kubernetes.io/component: operation
    app.kubernetes.io/part-of: pitflow
    app.kubernetes.io/managed-by: github-actions
spec:
  selector:
    app.kubernetes.io/name: pitflow-backend
    app.kubernetes.io/instance: pitflow-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
