name: Teste get Secrets

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false


jobs:
# -------------------------------------------------------------------------
# JOB 1: FETCH SECRETS DO AWS SECRETS MANAGER
# -------------------------------------------------------------------------
  secrets:
    name: Fetch Secrets from AWS Secrets Manager
    runs-on: ubuntu-latest
    outputs:
      ecr_url: ${{ steps.values.outputs.ecr_url }}
      eks_cluster_name: ${{ steps.values.outputs.eks_cluster_name }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch Infrastructure Secrets
        id: values
        run: |
          set -eo pipefail
          echo "🔐 Buscando secret 'pitflow/bootstrap'..."

          INFRA_JSON=$(aws secretsmanager get-secret-value \
            --secret-id "pitflow/bootstrap" \
            --query SecretString \
            --output text) || {
              echo "❌ Falha ao buscar secret 'pitflow/bootstrap'. Verifique se o secret existe e se as credenciais têm permissão."
              exit 1
            }

          ECR_URL=$(echo "$INFRA_JSON"          | jq -r '.ECR_URL')
          EKS_CLUSTER_NAME=$(echo "$INFRA_JSON" | jq -r '.EKS_CLUSTER_NAME')

          # Validação
          if [ -z "$ECR_URL" ] || [ "$ECR_URL" = "null" ]; then
            echo "❌ ECR_URL não encontrada"
            exit 1
          fi

          if [ -z "$EKS_CLUSTER_NAME" ] || [ "$EKS_CLUSTER_NAME" = "null" ]; then
            echo "❌ EKS_CLUSTER_NAME não encontrada"
            exit 1
          fi

          echo "ecr_url=${ECR_URL}" >> $GITHUB_OUTPUT
          echo "eks_cluster_name=${EKS_CLUSTER_NAME}" >> $GITHUB_OUTPUT

          echo "✅ Secret de infraestrutura obtido e mascarado com sucesso."

  print:
    name: Print variables from secretmanager
    needs: [secrets]
    runs-on: ubuntu-latest
    steps:
      - name: Verify variables
        env:
          ECR_URL: ${{ needs['fetch-secrets'].outputs.ecr_url }}
          EKS_CLUSTER_NAME: ${{ needs['fetch-secrets'].outputs.eks_cluster_name }}
        run: |
          set -eo pipefail

          echo "=== DEBUG INFO ==="
          echo "ECR_URL from env: '${ECR_URL}'"
          echo "ECR_URL length: ${#ECR_URL}"
          
          echo "EKS_CLUSTER_NAME from env: '${EKS_CLUSTER_NAME}'"
          echo "EKS_CLUSTER_NAME length: ${#EKS_CLUSTER_NAME}"
          
          echo "needs context: ${{ toJson(needs.secrets.outputs) }}"
          echo "================="
          
